### ISSUE TITLE
Rocket.Chat Team Handbook TOC links don't work

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/rocketchat.github.io#132]
Clicking on a Table of Contents link sends you to a "Whoops we can't find it" page.
![image](https://user-images.githubusercontent.com/1986378/36861345-5f9fba5a-1d62-11e8-98f1-0012bddce4f1.png)

**Comment by engelgabriel** [comment]
The ToC at https://rocketchat.github.io/handbook/marketing/ works but the one at https://rocketchat.github.io/handbook/onboarding/ does not.

**Comment by engelgabriel** [comment]
moved handbook to https://github.com/RocketChat/handbook
