### ISSUE TITLE
Broken blog post

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/rocketchat.github.io#163]
![image](https://user-images.githubusercontent.com/51996/38056027-e610018c-32a0-11e8-9d3d-3225fcfea091.png)

This article: 
https://rocket.chat/2018/03/26/2017-01-04-creating-facebook-of-stocks/

On page 5 as of right now: https://rocket.chat/blog/page/5/

**Comment by SeanPackham** [comment]
Isabella updated the image a week ago. https://rocket.chat/2017/01/04/creating-facebook-of-stocks/
I am removing the post's first heading so the card displays a snippet of the copy https://github.com/RocketChat/rocketchat.github.io/pull/195
