### ISSUE TITLE
Curvestone Interview - TuttorFair

### ISSUE THREAD

**Issue by juliagrala** [RocketChat/rocketchat.github.io#20]
This company will probably be our first reseller partner in Europe and they have good cases of use of Rocket.Chat, because they have being implementing it in different projects, like Tuttorfair. 
Here is the complete article about it, they got a spot on British news: http://blog.curvestone.io/ondemand_tutorfair_app/

Sebastian is the CTO and he agreed on doing an interview about this project 3 days ago.
Sebastian Kotur <seb@curvestone.io>

**Comment by SeanPackham** [comment]
@juliagrala please see https://github.com/RocketChat/rocketchat.github.io/issues/20#issuecomment-352001124

**Comment by SeanPackham** [comment]
Moving internal blog post requests to Asana.

**Comment by Sing-Li** [comment]
Blog posts featuring community members are not internal.

**Comment by SeanPackham** [comment]
Gabriel requested I add checklist to our handbook to assess content and layout our publishing process https://rocketchat.github.io/handbook/marketing/#what-we-publish
