### ISSUE TITLE
Join the Rocket.Chat community -> Endless Customization

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/rocketchat.github.io#245]
This area is less about the community

![image](https://user-images.githubusercontent.com/1000217/40373023-62067f6e-5dbc-11e8-9973-9986128f1d25.png)

And more about the "Endless Customization" you can do with opensource.

So we should replace the titles and use a improved version of the description from:

<img width="589" alt="screen shot 2018-05-22 at 12 36 36" src="https://user-images.githubusercontent.com/1000217/40373230-d0d75e7c-5dbc-11e8-96e3-c4436692dbb1.png">

And  we need a new illustration to use for community.

**Comment by isabellarussell** [comment]
I disagree. I think it's important for us to have a section on Community and the Open Source nature of RC. It is what distinguishes us from other platforms.
What we can look at doing instead is adding an open source dimension to the Customization part.
We can also replace the Community illustration. I can talk to Significa about this today.

**Comment by engelgabriel** [comment]
Let's discuss this via voice.
