### ISSUE TITLE
Blog pages have different sizing

### ISSUE THREAD

**Issue by juliagrala** [RocketChat/rocketchat.github.io#250]
From the menu icons to the page's text, all changes when you move from Blog Home to any other subpage, like events. 
Home:
![image](https://user-images.githubusercontent.com/30629556/40380265-f864047e-5dce-11e8-855d-83301746d004.png)
Events:
![image](https://user-images.githubusercontent.com/30629556/40380269-fdb69662-5dce-11e8-8055-0c8e16c603cf.png)

**Comment by isabellarussell** [comment]
All the blog category pages are the same, it is just the Events page that has larger boxes, so that it is differentiated from the blog pages. If you think this is an issue, we can revisit for v.2. Closing for now.
