### ISSUE TITLE
Events page format

### ISSUE THREAD

**Issue by juliagrala** [RocketChat/rocketchat.github.io#251]
The page's layout is towards a blog and not a calendar, what makes this page confusing. 
It would be better to have a calendar and the events organized by date, not like blog posts with a date. 
![image](https://user-images.githubusercontent.com/30629556/40380374-4d26b2a4-5dcf-11e8-850d-d3e337b27fae.png)

**Comment by isabellarussell** [comment]
Thanks for the feedback Julia. This is a design issue so is not quickly solvable for this version.
I will work it into v.2 though as I see your point.
