### ISSUE TITLE
Menu not being responsive correctly

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/rocketchat.github.io#252]
![screen shot 2018-05-22 at 12 08 36 pm](https://user-images.githubusercontent.com/234261/40384340-9b7628ea-5dd9-11e8-840b-6901e026183d.png)
![screen shot 2018-05-22 at 12 09 33 pm](https://user-images.githubusercontent.com/234261/40384345-9ef43f2a-5dd9-11e8-9947-e14a41062201.png)
![screen shot 2018-05-22 at 12 11 44 pm](https://user-images.githubusercontent.com/234261/40384349-a16aee5c-5dd9-11e8-80a5-a58441ef16bc.png)

**Comment by isabellarussell** [comment]
Definitely an issue. @danilowoz can you fix it?
