### ISSUE TITLE
Main title and description being cut

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/rocketchat.github.io#254]
![screen shot 2018-05-22 at 12 12 11 pm](https://user-images.githubusercontent.com/234261/40384477-0d1477a4-5dda-11e8-8ab9-c3953aa20c19.png)
![screen shot 2018-05-22 at 12 12 01 pm](https://user-images.githubusercontent.com/234261/40384478-0d3857fa-5dda-11e8-9408-f57af4c9ead9.png)

**Comment by isabellarussell** [comment]
@danilowoz can you take a look and fix this first thing?
