### ISSUE TITLE
Same description for all three Cloud tiers

### ISSUE THREAD

**Issue by antsar** [RocketChat/rocketchat.github.io#261]
On the [Cloud page, the Pricing section](https://rocket.chat/cloud#pricing) has the same description text for all three tiers.

Presumably these should be different?

* [Small](https://github.com/RocketChat/rocketchat.github.io/blob/master/cloud.html#L116)
* [Medium](https://github.com/RocketChat/rocketchat.github.io/blob/master/cloud.html#L174)
* [Large](https://github.com/RocketChat/rocketchat.github.io/blob/master/cloud.html#L232)

**Comment by danilowoz** [comment]
My fault, it should be: 
- Small: For new & small teams or small communities
- Medium: For growing teams or communities with increased activity
- Large: For active or large enterprises or communities

Is that ok @isabellarussell

**Comment by isabellarussell** [comment]
@danilowoz yes that's good, please go ahead, thank you!
Thanks @antsar for spotting and signalling!
