### ISSUE TITLE
Contact form bug using Opera 52.0

### ISSUE THREAD

**Issue by juliagrala** [RocketChat/rocketchat.github.io#273]
It seems your online contact form does not work properly using Opera 52.0. I always get the following message "{"message":"Please provide name"}"

**Comment by danilowoz** [comment]
Hi @juliagrala 
How and who get this message? Because of this error, only appears on the API level, not on the front end, weird

**Comment by danilowoz** [comment]
Any news @juliagrala?

**Comment by engelgabriel** [comment]
Was this fixed?

**Comment by danilowoz** [comment]
I'm waiting for more information to understand where is the problem with it

**Comment by MartinSchoeler** [comment]
I've done some testing with opera and could not find anything wrong with the form, for now I will close this issue.
