### ISSUE TITLE
Changes into website's forms: Contact Form  + Partners Form

### ISSUE THREAD

**Issue by juliagrala** [RocketChat/rocketchat.github.io#278]
Sales team needs that the information that comes from our website forms goes to also to our CRM: https://rocketchat.agilecrm.com. Today we have 2 forms:

**1) https://rocket.chat/contact**
Inside AgileCRM: information should create a "new contact" and, if possible, all have the "contact source" as "contact form" and "contact status" as "needs qualification".
Fields required for the website form + respective fields in Agile:
Name   ------> First Name
Last Name --> Last Name
Company ---> Company
Title ---------> Title
Email---------> Email
Subject-------> Note1
Message-----> Note 2

**2) https://rocket.chat/become-partner/**
Inside AgileCRM: information should create a "new contact" and, if possible, all have the "contact source" as "contact form" and "contact status" as "potential partner".
Fields required for the website form + respective fields in Agile: https://docs.google.com/document/d/1BWN0ECryHLapK7xJtHzmzkNR0XYpZKN6-QvZChGhF30/edit?usp=sharing

**Comment by rodrigok** [comment]
@diegodorgam that would be awesome, do you have access to the node mail service repo?

**Comment by diegodorgam** [comment]
No I don't,

I was wondering in maybe use agilecrm with amazon ses for sending the
emails.

but in the case of the contact form, it wouldn't be necessary to send it
through e-mail though.


*Diego Dorgam*Sales & Bots

diego.dorgam@rocket.chat

+ 55 61 981830569 <+5561981830569>

@diego.dorgam <https://demo.rocket.chat/direct/diego.dorgam>

https://rocket.chat

2018-05-26 10:07 GMT-03:00 Rodrigo Nascimento <notifications@github.com>:

**Comment by isabellarussell** [comment]
@rodrigok @diegodorgam how is this issue resolution progressing?
