### ISSUE TITLE
Changed Windows logo conflicts with new theme box color

### ISSUE THREAD

**Issue by balcsida** [RocketChat/rocketchat.github.io#300]
When I created #174 I was not aware of the new site design and because of this, the Windows logo color conflicts with the background on the home page and on the download page as well (see screenshot above).
![image](https://user-images.githubusercontent.com/1768446/40877963-e232f444-6689-11e8-883b-0c85369ad06d.png)

I would like to apologize for overlooking this and I made PR #299 to use the white version of the logo.
Thank you for bearing with me! 🙂

**Comment by geekgonecrazy** [comment]
😁 it's all good.  We reviewed and didn't think of that.


Thanks for fixing!  Merged!
