### ISSUE TITLE
Update partner logo

### ISSUE THREAD

**Issue by juliagrala** [RocketChat/rocketchat.github.io#326]
![logo mconf](https://user-images.githubusercontent.com/30629556/41317946-1499740e-6e6d-11e8-9858-70e929b9b84b.png)

**Comment by danilowoz** [comment]
Hey @juliagrala 
May I change the type color to white? Because the others logos are like that and I think it'll be more readable. What do you think? I prefer to ask before changing a brand :)

**Comment by isabellarussell** [comment]
go for it! :)
