### ISSUE TITLE
Support pricing should say that's on a 1 year plan

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/rocketchat.github.io#338]
Even though our support plans say "From" before the price, nowhere it says the price listed corresponds to the annual payment (1,275 * 12 = $15300). I believe we need a * to indicate that's on a 1 year advanced payment.

**Comment by isabellarussell** [comment]
Thanks Marcelo.
In the FAQ section below the price table, it does indicate the prices are for an annual contract
![image](https://user-images.githubusercontent.com/36157246/41979079-1db7be7e-7a1b-11e8-8ba8-7e8156e012e8.png)

But we can make it more explicit if you would like, such as mentioning the advanced payment system?

**Comment by isabellarussell** [comment]
@marceloschmidt what are your thoughts on the above?

**Comment by marceloschmidt** [comment]
I think adding a * to it and referencing Pricing & Billing to make it clear it's annual would be good.
