### ISSUE TITLE
New Brazilian office: Update address on website

### ISSUE THREAD

**Issue by isabellarussell** [RocketChat/rocketchat.github.io#349]
@marceloschmidt please send over the new address so I can update the website contact page and other pages. Thanks!

**Comment by marceloschmidt** [comment]
Rua Dr. Jorge Fayet, 757 - Porto Alegre / RS - 91330-330, BRAZIL

Em ter, 3 de jul de 2018 12:04, Isabella Russell <notifications@github.com>
escreveu:
