### ISSUE TITLE
Need Uruguay flag

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/rocketchat.github.io#378]
Looks like we need a Uruguay flag so we can add Uruguay to the map.

Do we have a place we are getting the flags from?

**Comment by isabellarussell** [comment]
@thiagosanchz Could you help with this?

**Comment by MartinSchoeler** [comment]
They are simple images, it looks like they are simply using the emoji flags as `.png` files.

So adding a Uruquay.png to the flags folder should fix it.

**Comment by rssilva** [comment]
That's right, @MartinSchoeler! We would need a flag with this waving(?)/fluttering effect

**Comment by MartinSchoeler** [comment]
I've found one on this site https://emojipedia.org/flag-for-uruguay/ looks like our us flag comes from there too.
