### ISSUE TITLE
Formatting issue on Docs page

### ISSUE THREAD

**Issue by isabellarussell** [RocketChat/rocketchat.github.io#394]
A community member sent an email via contact form bringing to our attention a formatting issue on the Docs page:

![image](https://user-images.githubusercontent.com/36157246/43715526-a72dcf6e-9978-11e8-8e0a-11f17c83532b.png)

I have tested in on my end, and this eating up of words on the right-hand side of the box appears to occur when the user zooms in on their screen:

![image](https://user-images.githubusercontent.com/36157246/43715611-f5485bb0-9978-11e8-9c02-ad57793d66db.png)

If somebody could help, that would be great! Thanks

**Comment by MartinSchoeler** [comment]
@isabellarussell Working on it.
