### ISSUE TITLE
rocket.chat/images/mockup.png no longer exists

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/rocketchat.github.io#398]
`https://rocket.chat/images/mockup.png` no longer exists and is used for the intergrations preview.

**Comment by isabellarussell** [comment]
Hi Bradley! Can you assign somebody to this task who you feel could fix it? It will get fixed quicker. Cheers

**Comment by engelgabriel** [comment]
This MUST be an internal image provided by the Rocket.Chat server itself.

**Comment by graywolf336** [comment]
@engelgabriel while I agree that from here on out it should, up until that change is implemented inside of Rocket.Chat it looks broken on all versions.

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/commit/3b642b3e3e853e970cb82b025a05c76183b11f48
