### ISSUE TITLE
Decrease size of images

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/rocketchat.github.io#409]
![image](https://user-images.githubusercontent.com/51996/44237655-eed5c500-a176-11e8-8b79-62d2ac66985c.png)

These images account for many gigs of transfer.  We should probably decrease the size.  

Also related to the size.. these big images are the most common to not be completed downloading.

**Comment by balcsida** [comment]
I would recommend installing [ImgBot](https://github.com/marketplace/imgbot) to this repository.
This would automatically open a Pull Request with all the images losslessly optimized as soon as those touches this repo.
If that's too fast, it is also possible to [schedule this check](https://imgbot.net/docs#schedule) daily, weekly or monthly.

Opened PR #461 for this

**Comment by balcsida** [comment]
Found out that ImgBot is not that good in optimization.
Sending an another PR, #467

**Comment by engelgabriel** [comment]
Closed via #467 but we should add some automation check on our CI

**Comment by balcsida** [comment]
Also, is it possible to have certain graphics in PNG instead of JPG (e.g. the background rockets on the pricing page)?

**Comment by engelgabriel** [comment]
we will change all background with the original SVG.

**Comment by MartinSchoeler** [comment]
> 
> 
> Closed via #467 but we should add some automation check on our CI
