### ISSUE TITLE
Make concession discount more visible 

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/rocketchat.github.io#462]
Move this part of the FAQ to a more prominent section of the pricing page

![image](https://user-images.githubusercontent.com/1000217/46043852-7c4df280-c0ef-11e8-8a3c-b5e9291a58d0.png)

See Slack

![image](https://user-images.githubusercontent.com/1000217/46044040-0d24ce00-c0f0-11e8-8890-b866ac34518f.png)

**Comment by sunilsj99** [comment]
Can i work on this issue @engelgabriel ?? I am new to RocketChat and i want to start contributing in the organization.

**Comment by arthurgiustina** [comment]
@sunilsj99 

Thank you for your availability.

We are already working on this issue within the Rocket Chat team. You will soon see on the website.

You can continue to suggest improvements in other open issues.

Have a good week.
