### ISSUE TITLE
Turn the PRESS items into a BLOG category 

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/rocketchat.github.io#506]
* Merge the YML files
* Add option to open the LINK instead of a actual blog post
* Add the PRESS category to show in teh top of the blog page too
* Add bottom "Category Tag"+ "By zxc" line in the bottom

![image](https://user-images.githubusercontent.com/1000217/46879840-76f5e500-ce1d-11e8-9851-732726ca7f69.png)

![image](https://user-images.githubusercontent.com/1000217/46879883-8ffe9600-ce1d-11e8-8a3b-b508e1068b01.png)

**Comment by MartinSchoeler** [comment]
@engelgabriel Just a note, there is no way to merge the YML files as seen that the blog does not uses YML files, instead get their data directly from the posts fontmatter.
