### ISSUE TITLE
1 and 1 Hosting 

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/rocketchat.github.io#54]
This is a large and well-known hosting company deploying Rocket.Chat internally.

They are willing to be interviewed to talk about how they use Rocket.Chat to simplify their operations internally.

Please contact:

Timm Friebe tfriebe@united-internet.de

and his direct report:  Finn Glöe ,   login@amshaegar.de

**Comment by SeanPackham** [comment]
@Sing-Li is there anything unique about their usage of Rocket.Chat that warrants a case study or feature?

**Comment by SeanPackham** [comment]
Moving internal blog post requests to Asana.

**Comment by Sing-Li** [comment]
Blog posts featuring community members are not internal.

**Comment by SeanPackham** [comment]
Gabriel requested I add checklist to our handbook to assess content and layout our publishing process https://rocketchat.github.io/handbook/marketing/#what-we-publish
