### ISSUE TITLE
Activate event link when clicked on - Blog Events page

### ISSUE THREAD

**Issue by isabellarussell** [RocketChat/rocketchat.github.io#540]
I'd like the event to link to the actual official event website, because I include a link in the code but this does not get used:
![screen shot 2018-10-25 at 15 19 58](https://user-images.githubusercontent.com/36157246/47507115-76237100-d869-11e8-809d-20ea02827886.png)

At the moment, when the user clicks on the event, it just sends them to an empty blog post with the logo. This does not achieve anything.
Instead, they should be taken to the linked address so they can more info about the event.

So we would get rid of this: 
![image](https://user-images.githubusercontent.com/36157246/47507215-ab2fc380-d869-11e8-9248-00095c34c8c7.png)

**Comment by MartinSchoeler** [comment]
With the changes in the #539 PR, we will be able to do this, instead of using `link` we should use `extUrl`
