### ISSUE TITLE
Promoting Apps with Smart App Banners

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/rocketchat.github.io#581]
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html

https://medium.com/@qinaliu/promoting-ios-apps-with-smart-app-banners-c3c769ab7470

**Comment by Rodriq** [comment]
Hey @engelgabriel @MartinSchoeler
 About this issue is there any current work going on?
maybe I could do something about it.
Rocket Chat id on Appstore is `1148741252`

**Comment by geekgonecrazy** [comment]
![img_0738](https://user-images.githubusercontent.com/51996/53775477-586db480-3eb8-11e9-8d21-f4bc84833809.PNG)


looks like this actually already implemented.

@MartinSchoeler please reopen if not so
