### ISSUE TITLE
Reduce space from the tabs and the pricing table

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/rocketchat.github.io#582]
![screen shot 2018-11-07 at 14 35 09](https://user-images.githubusercontent.com/551004/48917036-f5599400-ee6b-11e8-9c97-ee271f03848a.png)

Ideally they would fit together in the same screen.

**Comment by engelgabriel** [comment]
![image](https://user-images.githubusercontent.com/1000217/48917071-13bf8f80-ee6c-11e8-917c-840b4d587ed6.png)

**Comment by engelgabriel** [comment]
could even add a 10px space between the cards

**Comment by MartinSchoeler** [comment]
Done!
