### ISSUE TITLE
Move DATEs to top line on event blocks

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/rocketchat.github.io#630]
Make the date on

![image](https://user-images.githubusercontent.com/1000217/51276603-442f3000-19bc-11e9-9b53-e1d386696b1b.png)

The same as 

![image](https://user-images.githubusercontent.com/1000217/51276630-5f9a3b00-19bc-11e9-893c-9f6671100967.png)

And use MMM dd, YYYY as the date format everywhere on the website.

**Comment by MartinSchoeler** [comment]
![screen shot 2019-01-18 at 11 17 15](https://user-images.githubusercontent.com/20868078/51389185-a732db00-1b12-11e9-8f6b-b7ccb23f1990.png)

Done!
