### ISSUE TITLE
Question about form data

### ISSUE THREAD

**Issue by MrHpower** [RocketChat/rocketchat.github.io#640]
Hi guys,

Great Project and website!

I'm wondering how the contact form data is send to a mailbox or database?

In form.js there is:

var formHelpers = {
	url: '//contactmailer.rocket.chat',
...
Am guessing the Json data is send to the website contactmailer.rocket.chat/mail.
But how is it received?
When i got to the website it only says "Working!"

What is idea behind this?

Great Job and keep up the good support, thnx!

**Comment by MartinSchoeler** [comment]
The site sends the JSON data to contact mailer via POST api call, the contact mailer is a service written by us that runs on our own infrastructure. The code for this service is private, so if you have any suggestions of changes, you can find me at https://open.rocket.chat/direct/martin.schoeler
