### ISSUE TITLE
Promo text get covered on the main website. Cannot read.

### ISSUE THREAD

**Issue by minimedj** [RocketChat/rocketchat.github.io#677]
Here is all you need: https://monosnap.com/file/SLhHG8srHciAflLEE1dAZrSnq921Vh

**Comment by minimedj** [comment]
@Rodriq I have iMac 27 retina. I never use browser full screen. Just play with screen resizing to find a bug.

**Comment by Rodriq** [comment]
> @Rodriq I have iMac 27 retina. I never use browser full screen. Just play with screen resizing to find a bug.

okay cool!
  The patch I sent, I think will be able to handle that. On some Ex.Large screen, the image shrinks. So I tried taking care of that.

**Comment by Rodriq** [comment]
@marceloschmidt this issue has been taken care of by #666 
Should be closed.

**Comment by marceloschmidt** [comment]
Thanks
