### ISSUE TITLE
Is this button background by design?

### ISSUE THREAD

**Issue by lolimay** [RocketChat/rocketchat.github.io#681]
![image](https://user-images.githubusercontent.com/32427260/55274810-8a3b3500-5317-11e9-9f3f-775ef8d11187.png)

I've noticed that there is a `#030c1a` background behind the <kbd>View Migration Docs
</kbd> button in the page [https://rocket.chat/atlassian](https://rocket.chat/atlassian).

Is this by design or a mistake?

**Comment by MartinSchoeler** [comment]
Closed by #679
