### ISSUE TITLE
Submenu text color not visible on /atlassian

### ISSUE THREAD

**Issue by antkaz** [RocketChat/rocketchat.github.io#715]
Hello.
Text merges with the background
![image](https://user-images.githubusercontent.com/19654261/62921511-61957280-bdc2-11e9-9493-0e66f277a3da.png)

**Comment by Rodriq** [comment]
@marceloschmidt  We no longer face this issue. Best it's closed.


![image](https://user-images.githubusercontent.com/39289592/74040641-5bc0c880-49c4-11ea-89e7-ab596f1ba058.png)

**Comment by marceloschmidt** [comment]
Thanks
