### ISSUE TITLE
The contact sales button looks a little strange

### ISSUE THREAD

**Issue by lolimay** [RocketChat/rocketchat.github.io#734]
![image](https://user-images.githubusercontent.com/32427260/66205138-30109780-e6df-11e9-8b28-07b0bf583e4d.png)

Source: https://rocket.chat/atlassian (at the bottom of the page)

**Comment by Rodriq** [comment]
@marceloschmidt I think this issue should be closed.
It's been handled by this commit [3cfebbf](https://github.com/RocketChat/rocketchat.github.io/commit/3cfebbf2251db4449cf761b971e459a32a95b13e)

![image](https://user-images.githubusercontent.com/39289592/74039460-23b88600-49c2-11ea-8ac8-0b8c3f1f8fce.png)

**Comment by marceloschmidt** [comment]
Thanks
