### ISSUE TITLE
"Mobile and Desktop Apps" links to ancient 2.7.0 versions

### ISSUE THREAD

**Issue by martinvonwittich** [RocketChat/rocketchat.github.io#85]
https://rocket.chat/docs/installation/mobile-and-desktop-apps/ links to the ancient version 2.7.0 of the RocketChat client:

https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.7.0/rocketchat-desktop-setup-2.7.0.exe
https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.7.0/rocketchat-desktop-2.7.0.dmg
https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.7.0/rocketchat-desktop_2.7.0_amd64.deb
https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.7.0/rocketchat-desktop_2.7.0_i386.deb
https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.7.0/rocketchat-desktop-2.7.0.rpm

https://rocket.chat/download links to the most recent version instead (2.10.2 at the time of writing). I don't really see any point to the "Mobile and Desktop Apps" site when the normal download site works fine and is regularly updated; maybe the "Mobile and Desktop Apps" should just link the normal download site?

**Comment by SeanPackham** [comment]
Thank you for reporting @martinvonwittich

**Comment by SeanPackham** [comment]
@MartinSchoeler could you remove the download instructions (links) from this [documentation article](https://rocket.chat/docs/installation/mobile-and-desktop-apps/) and link to our website page for people to get the most up-to-date download links.

**Comment by SeanPackham** [comment]
Opened as issue in docs https://github.com/RocketChat/docs/issues/549
